#!/bin/sh

architectures="powerpc s390x"
buildarch=`dpkg-architecture -qDEB_BUILD_ARCH`

echo $architectures | grep -q $buildarch
if [ $? -eq 0 ]
then
	update-alternatives --set fakeroot /usr/bin/fakeroot-tcp
fi
